// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

// Export members:
export * from "./lxccontainer";
export * from "./lxcdisk";
export * from "./pool";
export * from "./qemuVM";

// Import resources to register:
import { LXCContainer } from "./lxccontainer";
import { LXCDisk } from "./lxcdisk";
import { Pool } from "./pool";
import { QemuVM } from "./qemuVM";

const _module = {
    version: utilities.getVersion(),
    construct: (name: string, type: string, urn: string): pulumi.Resource => {
        switch (type) {
            case "proxmoxve:proxmox/lXCContainer:LXCContainer":
                return new LXCContainer(name, <any>undefined, { urn })
            case "proxmoxve:proxmox/lXCDisk:LXCDisk":
                return new LXCDisk(name, <any>undefined, { urn })
            case "proxmoxve:proxmox/pool:Pool":
                return new Pool(name, <any>undefined, { urn })
            case "proxmoxve:proxmox/qemuVM:QemuVM":
                return new QemuVM(name, <any>undefined, { urn })
            default:
                throw new Error(`unknown resource type ${type}`);
        }
    },
};
pulumi.runtime.registerResourceModule("proxmoxve", "proxmox/lXCContainer", _module)
pulumi.runtime.registerResourceModule("proxmoxve", "proxmox/lXCDisk", _module)
pulumi.runtime.registerResourceModule("proxmoxve", "proxmox/pool", _module)
pulumi.runtime.registerResourceModule("proxmoxve", "proxmox/qemuVM", _module)
