// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import { input as inputs, output as outputs } from "../types";

export interface QemuVMDisk {
    aio?: pulumi.Input<string>;
    backup?: pulumi.Input<number>;
    cache?: pulumi.Input<string>;
    discard?: pulumi.Input<string>;
    file?: pulumi.Input<string>;
    format?: pulumi.Input<string>;
    iops?: pulumi.Input<number>;
    iopsMax?: pulumi.Input<number>;
    iopsMaxLength?: pulumi.Input<number>;
    iopsRd?: pulumi.Input<number>;
    iopsRdMax?: pulumi.Input<number>;
    iopsRdMaxLength?: pulumi.Input<number>;
    iopsWr?: pulumi.Input<number>;
    iopsWrMax?: pulumi.Input<number>;
    iopsWrMaxLength?: pulumi.Input<number>;
    iothread?: pulumi.Input<number>;
    mbps?: pulumi.Input<number>;
    mbpsRd?: pulumi.Input<number>;
    mbpsRdMax?: pulumi.Input<number>;
    mbpsWr?: pulumi.Input<number>;
    mbpsWrMax?: pulumi.Input<number>;
    media?: pulumi.Input<string>;
    replicate?: pulumi.Input<number>;
    size: pulumi.Input<string>;
    slot?: pulumi.Input<number>;
    ssd?: pulumi.Input<number>;
    storage: pulumi.Input<string>;
    storageType?: pulumi.Input<string>;
    type: pulumi.Input<string>;
    volume?: pulumi.Input<string>;
}

export interface QemuVMHostpci {
    host?: pulumi.Input<string>;
    pcie?: pulumi.Input<number>;
    rombar?: pulumi.Input<number>;
}

export interface QemuVMNetwork {
    bridge?: pulumi.Input<string>;
    firewall?: pulumi.Input<boolean>;
    linkDown?: pulumi.Input<boolean>;
    macaddr?: pulumi.Input<string>;
    model: pulumi.Input<string>;
    mtu?: pulumi.Input<number>;
    queues?: pulumi.Input<number>;
    rate?: pulumi.Input<number>;
    tag?: pulumi.Input<number>;
}

export interface QemuVMSerial {
    id: pulumi.Input<number>;
    type: pulumi.Input<string>;
}

export interface QemuVMUnusedDisk {
    file?: pulumi.Input<string>;
    slot?: pulumi.Input<number>;
    storage?: pulumi.Input<string>;
}

export interface QemuVMUsb {
    host: pulumi.Input<string>;
    usb3?: pulumi.Input<boolean>;
}

export interface QemuVMVga {
    memory?: pulumi.Input<number>;
    type?: pulumi.Input<string>;
}
