// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import { input as inputs, output as outputs } from "../types";

export namespace proxmox {
    export interface LXCContainerFeatures {
        fuse?: boolean;
        keyctl?: boolean;
        mknod?: boolean;
        mount?: string;
        nesting?: boolean;
    }

    export interface LXCContainerMountpoint {
        acl?: boolean;
        backup?: boolean;
        file: string;
        key: string;
        mp: string;
        quota?: boolean;
        replicate?: boolean;
        shared?: boolean;
        size: string;
        slot: number;
        storage: string;
        volume: string;
    }

    export interface LXCContainerNetwork {
        bridge?: string;
        firewall?: boolean;
        gw?: string;
        gw6?: string;
        hwaddr: string;
        ip?: string;
        ip6?: string;
        mtu?: number;
        name: string;
        rate?: number;
        tag: number;
        trunks: string;
        type: string;
    }

    export interface LXCContainerRootfs {
        acl?: boolean;
        quota?: boolean;
        replicate?: boolean;
        ro?: boolean;
        shared?: boolean;
        size: string;
        storage: string;
        volume: string;
    }

    export interface LXCDiskMountoptions {
        noatime?: boolean;
        nodev?: boolean;
        noexec?: string;
        nosuid?: boolean;
    }

    export interface QemuVMDisk {
        aio?: string;
        backup?: number;
        cache?: string;
        discard?: string;
        file: string;
        format: string;
        iops?: number;
        iopsMax?: number;
        iopsMaxLength?: number;
        iopsRd?: number;
        iopsRdMax?: number;
        iopsRdMaxLength?: number;
        iopsWr?: number;
        iopsWrMax?: number;
        iopsWrMaxLength?: number;
        iothread?: number;
        mbps?: number;
        mbpsRd?: number;
        mbpsRdMax?: number;
        mbpsWr?: number;
        mbpsWrMax?: number;
        media: string;
        replicate?: number;
        size: string;
        slot: number;
        ssd?: number;
        storage: string;
        storageType: string;
        type: string;
        volume: string;
    }

    export interface QemuVMHostpci {
        host?: string;
        pcie?: number;
        rombar?: number;
    }

    export interface QemuVMNetwork {
        bridge?: string;
        firewall?: boolean;
        linkDown?: boolean;
        macaddr: string;
        model: string;
        mtu?: number;
        queues: number;
        rate: number;
        tag?: number;
    }

    export interface QemuVMSerial {
        id: number;
        type: string;
    }

    export interface QemuVMUnusedDisk {
        file: string;
        slot: number;
        storage: string;
    }

    export interface QemuVMUsb {
        host: string;
        usb3?: boolean;
    }

    export interface QemuVMVga {
        memory?: number;
        type?: string;
    }

}
