// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import { input as inputs, output as outputs } from "../types";

export interface QemuVMDisk {
    aio?: string;
    backup?: number;
    cache?: string;
    discard?: string;
    file: string;
    format: string;
    iops?: number;
    iopsMax?: number;
    iopsMaxLength?: number;
    iopsRd?: number;
    iopsRdMax?: number;
    iopsRdMaxLength?: number;
    iopsWr?: number;
    iopsWrMax?: number;
    iopsWrMaxLength?: number;
    iothread?: number;
    mbps?: number;
    mbpsRd?: number;
    mbpsRdMax?: number;
    mbpsWr?: number;
    mbpsWrMax?: number;
    media: string;
    replicate?: number;
    size: string;
    slot: number;
    ssd?: number;
    storage: string;
    storageType: string;
    type: string;
    volume: string;
}

export interface QemuVMHostpci {
    host?: string;
    pcie?: number;
    rombar?: number;
}

export interface QemuVMNetwork {
    bridge?: string;
    firewall?: boolean;
    linkDown?: boolean;
    macaddr: string;
    model: string;
    mtu?: number;
    queues: number;
    rate: number;
    tag?: number;
}

export interface QemuVMSerial {
    id: number;
    type: string;
}

export interface QemuVMUnusedDisk {
    file: string;
    slot: number;
    storage: string;
}

export interface QemuVMUsb {
    host: string;
    usb3?: boolean;
}

export interface QemuVMVga {
    memory?: number;
    type?: string;
}

