// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package proxmoxve

import (
	"context"
	"reflect"

	"github.com/pkg/errors"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type QemuVM struct {
	pulumi.CustomResourceState

	AdditionalWait pulumi.IntPtrOutput    `pulumi:"additionalWait"`
	Agent          pulumi.IntPtrOutput    `pulumi:"agent"`
	Args           pulumi.StringPtrOutput `pulumi:"args"`
	// Automatically reboot the VM if any of the modified parameters requires a reboot to take effect.
	AutomaticReboot pulumi.BoolPtrOutput `pulumi:"automaticReboot"`
	Balloon         pulumi.IntPtrOutput  `pulumi:"balloon"`
	// The VM bios, it can be seabios or ovmf
	Bios pulumi.StringPtrOutput `pulumi:"bios"`
	// Boot order of the VM
	Boot     pulumi.StringPtrOutput `pulumi:"boot"`
	Bootdisk pulumi.StringOutput    `pulumi:"bootdisk"`
	// Deprecated: Use `network.bridge` instead
	Bridge                pulumi.StringPtrOutput `pulumi:"bridge"`
	CiWait                pulumi.IntPtrOutput    `pulumi:"ciWait"`
	Cicustom              pulumi.StringPtrOutput `pulumi:"cicustom"`
	Cipassword            pulumi.StringPtrOutput `pulumi:"cipassword"`
	Ciuser                pulumi.StringPtrOutput `pulumi:"ciuser"`
	Clone                 pulumi.StringPtrOutput `pulumi:"clone"`
	CloneWait             pulumi.IntPtrOutput    `pulumi:"cloneWait"`
	CloudinitCdromStorage pulumi.StringPtrOutput `pulumi:"cloudinitCdromStorage"`
	Cores                 pulumi.IntPtrOutput    `pulumi:"cores"`
	Cpu                   pulumi.StringPtrOutput `pulumi:"cpu"`
	// Use to track vm ipv4 address
	DefaultIpv4Address pulumi.StringOutput `pulumi:"defaultIpv4Address"`
	// By default define SSH for provisioner info
	DefineConnectionInfo pulumi.BoolPtrOutput `pulumi:"defineConnectionInfo"`
	// The VM description
	Desc pulumi.StringPtrOutput `pulumi:"desc"`
	// Deprecated: Use `disk.size` instead
	DiskGb                  pulumi.Float64PtrOutput `pulumi:"diskGb"`
	Disks                   QemuVMDiskArrayOutput   `pulumi:"disks"`
	ForceCreate             pulumi.BoolPtrOutput    `pulumi:"forceCreate"`
	ForceRecreateOnChangeOf pulumi.StringPtrOutput  `pulumi:"forceRecreateOnChangeOf"`
	FullClone               pulumi.BoolPtrOutput    `pulumi:"fullClone"`
	// Deprecated: Use custom per-resource timeout instead. See https://www.terraform.io/docs/language/resources/syntax.html#operation-timeouts
	GuestAgentReadyTimeout pulumi.IntPtrOutput      `pulumi:"guestAgentReadyTimeout"`
	Hagroup                pulumi.StringPtrOutput   `pulumi:"hagroup"`
	Hastate                pulumi.StringPtrOutput   `pulumi:"hastate"`
	Hostpcis               QemuVMHostpciArrayOutput `pulumi:"hostpcis"`
	Hotplug                pulumi.StringPtrOutput   `pulumi:"hotplug"`
	Ipconfig0              pulumi.StringPtrOutput   `pulumi:"ipconfig0"`
	Ipconfig1              pulumi.StringPtrOutput   `pulumi:"ipconfig1"`
	Ipconfig10             pulumi.StringPtrOutput   `pulumi:"ipconfig10"`
	Ipconfig11             pulumi.StringPtrOutput   `pulumi:"ipconfig11"`
	Ipconfig12             pulumi.StringPtrOutput   `pulumi:"ipconfig12"`
	Ipconfig13             pulumi.StringPtrOutput   `pulumi:"ipconfig13"`
	Ipconfig14             pulumi.StringPtrOutput   `pulumi:"ipconfig14"`
	Ipconfig15             pulumi.StringPtrOutput   `pulumi:"ipconfig15"`
	Ipconfig2              pulumi.StringPtrOutput   `pulumi:"ipconfig2"`
	Ipconfig3              pulumi.StringPtrOutput   `pulumi:"ipconfig3"`
	Ipconfig4              pulumi.StringPtrOutput   `pulumi:"ipconfig4"`
	Ipconfig5              pulumi.StringPtrOutput   `pulumi:"ipconfig5"`
	Ipconfig6              pulumi.StringPtrOutput   `pulumi:"ipconfig6"`
	Ipconfig7              pulumi.StringPtrOutput   `pulumi:"ipconfig7"`
	Ipconfig8              pulumi.StringPtrOutput   `pulumi:"ipconfig8"`
	Ipconfig9              pulumi.StringPtrOutput   `pulumi:"ipconfig9"`
	Iso                    pulumi.StringPtrOutput   `pulumi:"iso"`
	Kvm                    pulumi.BoolPtrOutput     `pulumi:"kvm"`
	// Deprecated: Use `network.macaddr` to access the auto generated MAC address
	Mac    pulumi.StringPtrOutput `pulumi:"mac"`
	Memory pulumi.IntPtrOutput    `pulumi:"memory"`
	// The VM name
	Name       pulumi.StringOutput      `pulumi:"name"`
	Nameserver pulumi.StringOutput      `pulumi:"nameserver"`
	Networks   QemuVMNetworkArrayOutput `pulumi:"networks"`
	// Deprecated: Use `network` instead
	Nic  pulumi.StringPtrOutput `pulumi:"nic"`
	Numa pulumi.BoolPtrOutput   `pulumi:"numa"`
	// VM autostart on boot
	Onboot pulumi.BoolPtrOutput `pulumi:"onboot"`
	// VM autostart on create
	Oncreate        pulumi.BoolPtrOutput   `pulumi:"oncreate"`
	OsNetworkConfig pulumi.StringPtrOutput `pulumi:"osNetworkConfig"`
	OsType          pulumi.StringPtrOutput `pulumi:"osType"`
	Pool            pulumi.StringPtrOutput `pulumi:"pool"`
	// Deprecated: do not use anymore
	Preprovision pulumi.BoolPtrOutput   `pulumi:"preprovision"`
	Pxe          pulumi.BoolPtrOutput   `pulumi:"pxe"`
	QemuOs       pulumi.StringPtrOutput `pulumi:"qemuOs"`
	// Internal variable, true if any of the modified parameters requires a reboot to take effect.
	RebootRequired pulumi.BoolOutput       `pulumi:"rebootRequired"`
	Scsihw         pulumi.StringOutput     `pulumi:"scsihw"`
	Searchdomain   pulumi.StringOutput     `pulumi:"searchdomain"`
	Serials        QemuVMSerialArrayOutput `pulumi:"serials"`
	Sockets        pulumi.IntPtrOutput     `pulumi:"sockets"`
	// Use to pass instance ip address, redundant
	SshForwardIp  pulumi.StringPtrOutput `pulumi:"sshForwardIp"`
	SshHost       pulumi.StringOutput    `pulumi:"sshHost"`
	SshPort       pulumi.StringOutput    `pulumi:"sshPort"`
	SshPrivateKey pulumi.StringPtrOutput `pulumi:"sshPrivateKey"`
	SshUser       pulumi.StringPtrOutput `pulumi:"sshUser"`
	Sshkeys       pulumi.StringPtrOutput `pulumi:"sshkeys"`
	// Startup order of the VM
	Startup pulumi.StringPtrOutput `pulumi:"startup"`
	// Deprecated: Use `disk.storage` instead
	Storage pulumi.StringPtrOutput `pulumi:"storage"`
	// Deprecated: Use `disk.type` instead
	StorageType pulumi.StringPtrOutput `pulumi:"storageType"`
	// Enable tablet mode in the VM
	Tablet pulumi.BoolPtrOutput   `pulumi:"tablet"`
	Tags   pulumi.StringPtrOutput `pulumi:"tags"`
	// The node where VM goes to
	TargetNode pulumi.StringOutput `pulumi:"targetNode"`
	// Record unused disks in proxmox. This is intended to be read-only for now.
	UnusedDisks QemuVMUnusedDiskArrayOutput `pulumi:"unusedDisks"`
	Usbs        QemuVMUsbArrayOutput        `pulumi:"usbs"`
	Vcpus       pulumi.IntPtrOutput         `pulumi:"vcpus"`
	Vgas        QemuVMVgaArrayOutput        `pulumi:"vgas"`
	// Deprecated: Use `network.tag` instead
	Vlan pulumi.IntPtrOutput `pulumi:"vlan"`
	// The VM identifier in proxmox (100-999999999)
	Vmid pulumi.IntOutput `pulumi:"vmid"`
}

// NewQemuVM registers a new resource with the given unique name, arguments, and options.
func NewQemuVM(ctx *pulumi.Context,
	name string, args *QemuVMArgs, opts ...pulumi.ResourceOption) (*QemuVM, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.TargetNode == nil {
		return nil, errors.New("invalid value for required argument 'TargetNode'")
	}
	var resource QemuVM
	err := ctx.RegisterResource("proxmoxve:index/qemuVM:QemuVM", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetQemuVM gets an existing QemuVM resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetQemuVM(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *QemuVMState, opts ...pulumi.ResourceOption) (*QemuVM, error) {
	var resource QemuVM
	err := ctx.ReadResource("proxmoxve:index/qemuVM:QemuVM", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering QemuVM resources.
type qemuVMState struct {
	AdditionalWait *int    `pulumi:"additionalWait"`
	Agent          *int    `pulumi:"agent"`
	Args           *string `pulumi:"args"`
	// Automatically reboot the VM if any of the modified parameters requires a reboot to take effect.
	AutomaticReboot *bool `pulumi:"automaticReboot"`
	Balloon         *int  `pulumi:"balloon"`
	// The VM bios, it can be seabios or ovmf
	Bios *string `pulumi:"bios"`
	// Boot order of the VM
	Boot     *string `pulumi:"boot"`
	Bootdisk *string `pulumi:"bootdisk"`
	// Deprecated: Use `network.bridge` instead
	Bridge                *string `pulumi:"bridge"`
	CiWait                *int    `pulumi:"ciWait"`
	Cicustom              *string `pulumi:"cicustom"`
	Cipassword            *string `pulumi:"cipassword"`
	Ciuser                *string `pulumi:"ciuser"`
	Clone                 *string `pulumi:"clone"`
	CloneWait             *int    `pulumi:"cloneWait"`
	CloudinitCdromStorage *string `pulumi:"cloudinitCdromStorage"`
	Cores                 *int    `pulumi:"cores"`
	Cpu                   *string `pulumi:"cpu"`
	// Use to track vm ipv4 address
	DefaultIpv4Address *string `pulumi:"defaultIpv4Address"`
	// By default define SSH for provisioner info
	DefineConnectionInfo *bool `pulumi:"defineConnectionInfo"`
	// The VM description
	Desc *string `pulumi:"desc"`
	// Deprecated: Use `disk.size` instead
	DiskGb                  *float64     `pulumi:"diskGb"`
	Disks                   []QemuVMDisk `pulumi:"disks"`
	ForceCreate             *bool        `pulumi:"forceCreate"`
	ForceRecreateOnChangeOf *string      `pulumi:"forceRecreateOnChangeOf"`
	FullClone               *bool        `pulumi:"fullClone"`
	// Deprecated: Use custom per-resource timeout instead. See https://www.terraform.io/docs/language/resources/syntax.html#operation-timeouts
	GuestAgentReadyTimeout *int            `pulumi:"guestAgentReadyTimeout"`
	Hagroup                *string         `pulumi:"hagroup"`
	Hastate                *string         `pulumi:"hastate"`
	Hostpcis               []QemuVMHostpci `pulumi:"hostpcis"`
	Hotplug                *string         `pulumi:"hotplug"`
	Ipconfig0              *string         `pulumi:"ipconfig0"`
	Ipconfig1              *string         `pulumi:"ipconfig1"`
	Ipconfig10             *string         `pulumi:"ipconfig10"`
	Ipconfig11             *string         `pulumi:"ipconfig11"`
	Ipconfig12             *string         `pulumi:"ipconfig12"`
	Ipconfig13             *string         `pulumi:"ipconfig13"`
	Ipconfig14             *string         `pulumi:"ipconfig14"`
	Ipconfig15             *string         `pulumi:"ipconfig15"`
	Ipconfig2              *string         `pulumi:"ipconfig2"`
	Ipconfig3              *string         `pulumi:"ipconfig3"`
	Ipconfig4              *string         `pulumi:"ipconfig4"`
	Ipconfig5              *string         `pulumi:"ipconfig5"`
	Ipconfig6              *string         `pulumi:"ipconfig6"`
	Ipconfig7              *string         `pulumi:"ipconfig7"`
	Ipconfig8              *string         `pulumi:"ipconfig8"`
	Ipconfig9              *string         `pulumi:"ipconfig9"`
	Iso                    *string         `pulumi:"iso"`
	Kvm                    *bool           `pulumi:"kvm"`
	// Deprecated: Use `network.macaddr` to access the auto generated MAC address
	Mac    *string `pulumi:"mac"`
	Memory *int    `pulumi:"memory"`
	// The VM name
	Name       *string         `pulumi:"name"`
	Nameserver *string         `pulumi:"nameserver"`
	Networks   []QemuVMNetwork `pulumi:"networks"`
	// Deprecated: Use `network` instead
	Nic  *string `pulumi:"nic"`
	Numa *bool   `pulumi:"numa"`
	// VM autostart on boot
	Onboot *bool `pulumi:"onboot"`
	// VM autostart on create
	Oncreate        *bool   `pulumi:"oncreate"`
	OsNetworkConfig *string `pulumi:"osNetworkConfig"`
	OsType          *string `pulumi:"osType"`
	Pool            *string `pulumi:"pool"`
	// Deprecated: do not use anymore
	Preprovision *bool   `pulumi:"preprovision"`
	Pxe          *bool   `pulumi:"pxe"`
	QemuOs       *string `pulumi:"qemuOs"`
	// Internal variable, true if any of the modified parameters requires a reboot to take effect.
	RebootRequired *bool          `pulumi:"rebootRequired"`
	Scsihw         *string        `pulumi:"scsihw"`
	Searchdomain   *string        `pulumi:"searchdomain"`
	Serials        []QemuVMSerial `pulumi:"serials"`
	Sockets        *int           `pulumi:"sockets"`
	// Use to pass instance ip address, redundant
	SshForwardIp  *string `pulumi:"sshForwardIp"`
	SshHost       *string `pulumi:"sshHost"`
	SshPort       *string `pulumi:"sshPort"`
	SshPrivateKey *string `pulumi:"sshPrivateKey"`
	SshUser       *string `pulumi:"sshUser"`
	Sshkeys       *string `pulumi:"sshkeys"`
	// Startup order of the VM
	Startup *string `pulumi:"startup"`
	// Deprecated: Use `disk.storage` instead
	Storage *string `pulumi:"storage"`
	// Deprecated: Use `disk.type` instead
	StorageType *string `pulumi:"storageType"`
	// Enable tablet mode in the VM
	Tablet *bool   `pulumi:"tablet"`
	Tags   *string `pulumi:"tags"`
	// The node where VM goes to
	TargetNode *string `pulumi:"targetNode"`
	// Record unused disks in proxmox. This is intended to be read-only for now.
	UnusedDisks []QemuVMUnusedDisk `pulumi:"unusedDisks"`
	Usbs        []QemuVMUsb        `pulumi:"usbs"`
	Vcpus       *int               `pulumi:"vcpus"`
	Vgas        []QemuVMVga        `pulumi:"vgas"`
	// Deprecated: Use `network.tag` instead
	Vlan *int `pulumi:"vlan"`
	// The VM identifier in proxmox (100-999999999)
	Vmid *int `pulumi:"vmid"`
}

type QemuVMState struct {
	AdditionalWait pulumi.IntPtrInput
	Agent          pulumi.IntPtrInput
	Args           pulumi.StringPtrInput
	// Automatically reboot the VM if any of the modified parameters requires a reboot to take effect.
	AutomaticReboot pulumi.BoolPtrInput
	Balloon         pulumi.IntPtrInput
	// The VM bios, it can be seabios or ovmf
	Bios pulumi.StringPtrInput
	// Boot order of the VM
	Boot     pulumi.StringPtrInput
	Bootdisk pulumi.StringPtrInput
	// Deprecated: Use `network.bridge` instead
	Bridge                pulumi.StringPtrInput
	CiWait                pulumi.IntPtrInput
	Cicustom              pulumi.StringPtrInput
	Cipassword            pulumi.StringPtrInput
	Ciuser                pulumi.StringPtrInput
	Clone                 pulumi.StringPtrInput
	CloneWait             pulumi.IntPtrInput
	CloudinitCdromStorage pulumi.StringPtrInput
	Cores                 pulumi.IntPtrInput
	Cpu                   pulumi.StringPtrInput
	// Use to track vm ipv4 address
	DefaultIpv4Address pulumi.StringPtrInput
	// By default define SSH for provisioner info
	DefineConnectionInfo pulumi.BoolPtrInput
	// The VM description
	Desc pulumi.StringPtrInput
	// Deprecated: Use `disk.size` instead
	DiskGb                  pulumi.Float64PtrInput
	Disks                   QemuVMDiskArrayInput
	ForceCreate             pulumi.BoolPtrInput
	ForceRecreateOnChangeOf pulumi.StringPtrInput
	FullClone               pulumi.BoolPtrInput
	// Deprecated: Use custom per-resource timeout instead. See https://www.terraform.io/docs/language/resources/syntax.html#operation-timeouts
	GuestAgentReadyTimeout pulumi.IntPtrInput
	Hagroup                pulumi.StringPtrInput
	Hastate                pulumi.StringPtrInput
	Hostpcis               QemuVMHostpciArrayInput
	Hotplug                pulumi.StringPtrInput
	Ipconfig0              pulumi.StringPtrInput
	Ipconfig1              pulumi.StringPtrInput
	Ipconfig10             pulumi.StringPtrInput
	Ipconfig11             pulumi.StringPtrInput
	Ipconfig12             pulumi.StringPtrInput
	Ipconfig13             pulumi.StringPtrInput
	Ipconfig14             pulumi.StringPtrInput
	Ipconfig15             pulumi.StringPtrInput
	Ipconfig2              pulumi.StringPtrInput
	Ipconfig3              pulumi.StringPtrInput
	Ipconfig4              pulumi.StringPtrInput
	Ipconfig5              pulumi.StringPtrInput
	Ipconfig6              pulumi.StringPtrInput
	Ipconfig7              pulumi.StringPtrInput
	Ipconfig8              pulumi.StringPtrInput
	Ipconfig9              pulumi.StringPtrInput
	Iso                    pulumi.StringPtrInput
	Kvm                    pulumi.BoolPtrInput
	// Deprecated: Use `network.macaddr` to access the auto generated MAC address
	Mac    pulumi.StringPtrInput
	Memory pulumi.IntPtrInput
	// The VM name
	Name       pulumi.StringPtrInput
	Nameserver pulumi.StringPtrInput
	Networks   QemuVMNetworkArrayInput
	// Deprecated: Use `network` instead
	Nic  pulumi.StringPtrInput
	Numa pulumi.BoolPtrInput
	// VM autostart on boot
	Onboot pulumi.BoolPtrInput
	// VM autostart on create
	Oncreate        pulumi.BoolPtrInput
	OsNetworkConfig pulumi.StringPtrInput
	OsType          pulumi.StringPtrInput
	Pool            pulumi.StringPtrInput
	// Deprecated: do not use anymore
	Preprovision pulumi.BoolPtrInput
	Pxe          pulumi.BoolPtrInput
	QemuOs       pulumi.StringPtrInput
	// Internal variable, true if any of the modified parameters requires a reboot to take effect.
	RebootRequired pulumi.BoolPtrInput
	Scsihw         pulumi.StringPtrInput
	Searchdomain   pulumi.StringPtrInput
	Serials        QemuVMSerialArrayInput
	Sockets        pulumi.IntPtrInput
	// Use to pass instance ip address, redundant
	SshForwardIp  pulumi.StringPtrInput
	SshHost       pulumi.StringPtrInput
	SshPort       pulumi.StringPtrInput
	SshPrivateKey pulumi.StringPtrInput
	SshUser       pulumi.StringPtrInput
	Sshkeys       pulumi.StringPtrInput
	// Startup order of the VM
	Startup pulumi.StringPtrInput
	// Deprecated: Use `disk.storage` instead
	Storage pulumi.StringPtrInput
	// Deprecated: Use `disk.type` instead
	StorageType pulumi.StringPtrInput
	// Enable tablet mode in the VM
	Tablet pulumi.BoolPtrInput
	Tags   pulumi.StringPtrInput
	// The node where VM goes to
	TargetNode pulumi.StringPtrInput
	// Record unused disks in proxmox. This is intended to be read-only for now.
	UnusedDisks QemuVMUnusedDiskArrayInput
	Usbs        QemuVMUsbArrayInput
	Vcpus       pulumi.IntPtrInput
	Vgas        QemuVMVgaArrayInput
	// Deprecated: Use `network.tag` instead
	Vlan pulumi.IntPtrInput
	// The VM identifier in proxmox (100-999999999)
	Vmid pulumi.IntPtrInput
}

func (QemuVMState) ElementType() reflect.Type {
	return reflect.TypeOf((*qemuVMState)(nil)).Elem()
}

type qemuVMArgs struct {
	AdditionalWait *int    `pulumi:"additionalWait"`
	Agent          *int    `pulumi:"agent"`
	Args           *string `pulumi:"args"`
	// Automatically reboot the VM if any of the modified parameters requires a reboot to take effect.
	AutomaticReboot *bool `pulumi:"automaticReboot"`
	Balloon         *int  `pulumi:"balloon"`
	// The VM bios, it can be seabios or ovmf
	Bios *string `pulumi:"bios"`
	// Boot order of the VM
	Boot     *string `pulumi:"boot"`
	Bootdisk *string `pulumi:"bootdisk"`
	// Deprecated: Use `network.bridge` instead
	Bridge                *string `pulumi:"bridge"`
	CiWait                *int    `pulumi:"ciWait"`
	Cicustom              *string `pulumi:"cicustom"`
	Cipassword            *string `pulumi:"cipassword"`
	Ciuser                *string `pulumi:"ciuser"`
	Clone                 *string `pulumi:"clone"`
	CloneWait             *int    `pulumi:"cloneWait"`
	CloudinitCdromStorage *string `pulumi:"cloudinitCdromStorage"`
	Cores                 *int    `pulumi:"cores"`
	Cpu                   *string `pulumi:"cpu"`
	// By default define SSH for provisioner info
	DefineConnectionInfo *bool `pulumi:"defineConnectionInfo"`
	// The VM description
	Desc *string `pulumi:"desc"`
	// Deprecated: Use `disk.size` instead
	DiskGb                  *float64     `pulumi:"diskGb"`
	Disks                   []QemuVMDisk `pulumi:"disks"`
	ForceCreate             *bool        `pulumi:"forceCreate"`
	ForceRecreateOnChangeOf *string      `pulumi:"forceRecreateOnChangeOf"`
	FullClone               *bool        `pulumi:"fullClone"`
	// Deprecated: Use custom per-resource timeout instead. See https://www.terraform.io/docs/language/resources/syntax.html#operation-timeouts
	GuestAgentReadyTimeout *int            `pulumi:"guestAgentReadyTimeout"`
	Hagroup                *string         `pulumi:"hagroup"`
	Hastate                *string         `pulumi:"hastate"`
	Hostpcis               []QemuVMHostpci `pulumi:"hostpcis"`
	Hotplug                *string         `pulumi:"hotplug"`
	Ipconfig0              *string         `pulumi:"ipconfig0"`
	Ipconfig1              *string         `pulumi:"ipconfig1"`
	Ipconfig10             *string         `pulumi:"ipconfig10"`
	Ipconfig11             *string         `pulumi:"ipconfig11"`
	Ipconfig12             *string         `pulumi:"ipconfig12"`
	Ipconfig13             *string         `pulumi:"ipconfig13"`
	Ipconfig14             *string         `pulumi:"ipconfig14"`
	Ipconfig15             *string         `pulumi:"ipconfig15"`
	Ipconfig2              *string         `pulumi:"ipconfig2"`
	Ipconfig3              *string         `pulumi:"ipconfig3"`
	Ipconfig4              *string         `pulumi:"ipconfig4"`
	Ipconfig5              *string         `pulumi:"ipconfig5"`
	Ipconfig6              *string         `pulumi:"ipconfig6"`
	Ipconfig7              *string         `pulumi:"ipconfig7"`
	Ipconfig8              *string         `pulumi:"ipconfig8"`
	Ipconfig9              *string         `pulumi:"ipconfig9"`
	Iso                    *string         `pulumi:"iso"`
	Kvm                    *bool           `pulumi:"kvm"`
	// Deprecated: Use `network.macaddr` to access the auto generated MAC address
	Mac    *string `pulumi:"mac"`
	Memory *int    `pulumi:"memory"`
	// The VM name
	Name       *string         `pulumi:"name"`
	Nameserver *string         `pulumi:"nameserver"`
	Networks   []QemuVMNetwork `pulumi:"networks"`
	// Deprecated: Use `network` instead
	Nic  *string `pulumi:"nic"`
	Numa *bool   `pulumi:"numa"`
	// VM autostart on boot
	Onboot *bool `pulumi:"onboot"`
	// VM autostart on create
	Oncreate        *bool   `pulumi:"oncreate"`
	OsNetworkConfig *string `pulumi:"osNetworkConfig"`
	OsType          *string `pulumi:"osType"`
	Pool            *string `pulumi:"pool"`
	// Deprecated: do not use anymore
	Preprovision *bool          `pulumi:"preprovision"`
	Pxe          *bool          `pulumi:"pxe"`
	QemuOs       *string        `pulumi:"qemuOs"`
	Scsihw       *string        `pulumi:"scsihw"`
	Searchdomain *string        `pulumi:"searchdomain"`
	Serials      []QemuVMSerial `pulumi:"serials"`
	Sockets      *int           `pulumi:"sockets"`
	// Use to pass instance ip address, redundant
	SshForwardIp  *string `pulumi:"sshForwardIp"`
	SshPrivateKey *string `pulumi:"sshPrivateKey"`
	SshUser       *string `pulumi:"sshUser"`
	Sshkeys       *string `pulumi:"sshkeys"`
	// Startup order of the VM
	Startup *string `pulumi:"startup"`
	// Deprecated: Use `disk.storage` instead
	Storage *string `pulumi:"storage"`
	// Deprecated: Use `disk.type` instead
	StorageType *string `pulumi:"storageType"`
	// Enable tablet mode in the VM
	Tablet *bool   `pulumi:"tablet"`
	Tags   *string `pulumi:"tags"`
	// The node where VM goes to
	TargetNode string      `pulumi:"targetNode"`
	Usbs       []QemuVMUsb `pulumi:"usbs"`
	Vcpus      *int        `pulumi:"vcpus"`
	Vgas       []QemuVMVga `pulumi:"vgas"`
	// Deprecated: Use `network.tag` instead
	Vlan *int `pulumi:"vlan"`
	// The VM identifier in proxmox (100-999999999)
	Vmid *int `pulumi:"vmid"`
}

// The set of arguments for constructing a QemuVM resource.
type QemuVMArgs struct {
	AdditionalWait pulumi.IntPtrInput
	Agent          pulumi.IntPtrInput
	Args           pulumi.StringPtrInput
	// Automatically reboot the VM if any of the modified parameters requires a reboot to take effect.
	AutomaticReboot pulumi.BoolPtrInput
	Balloon         pulumi.IntPtrInput
	// The VM bios, it can be seabios or ovmf
	Bios pulumi.StringPtrInput
	// Boot order of the VM
	Boot     pulumi.StringPtrInput
	Bootdisk pulumi.StringPtrInput
	// Deprecated: Use `network.bridge` instead
	Bridge                pulumi.StringPtrInput
	CiWait                pulumi.IntPtrInput
	Cicustom              pulumi.StringPtrInput
	Cipassword            pulumi.StringPtrInput
	Ciuser                pulumi.StringPtrInput
	Clone                 pulumi.StringPtrInput
	CloneWait             pulumi.IntPtrInput
	CloudinitCdromStorage pulumi.StringPtrInput
	Cores                 pulumi.IntPtrInput
	Cpu                   pulumi.StringPtrInput
	// By default define SSH for provisioner info
	DefineConnectionInfo pulumi.BoolPtrInput
	// The VM description
	Desc pulumi.StringPtrInput
	// Deprecated: Use `disk.size` instead
	DiskGb                  pulumi.Float64PtrInput
	Disks                   QemuVMDiskArrayInput
	ForceCreate             pulumi.BoolPtrInput
	ForceRecreateOnChangeOf pulumi.StringPtrInput
	FullClone               pulumi.BoolPtrInput
	// Deprecated: Use custom per-resource timeout instead. See https://www.terraform.io/docs/language/resources/syntax.html#operation-timeouts
	GuestAgentReadyTimeout pulumi.IntPtrInput
	Hagroup                pulumi.StringPtrInput
	Hastate                pulumi.StringPtrInput
	Hostpcis               QemuVMHostpciArrayInput
	Hotplug                pulumi.StringPtrInput
	Ipconfig0              pulumi.StringPtrInput
	Ipconfig1              pulumi.StringPtrInput
	Ipconfig10             pulumi.StringPtrInput
	Ipconfig11             pulumi.StringPtrInput
	Ipconfig12             pulumi.StringPtrInput
	Ipconfig13             pulumi.StringPtrInput
	Ipconfig14             pulumi.StringPtrInput
	Ipconfig15             pulumi.StringPtrInput
	Ipconfig2              pulumi.StringPtrInput
	Ipconfig3              pulumi.StringPtrInput
	Ipconfig4              pulumi.StringPtrInput
	Ipconfig5              pulumi.StringPtrInput
	Ipconfig6              pulumi.StringPtrInput
	Ipconfig7              pulumi.StringPtrInput
	Ipconfig8              pulumi.StringPtrInput
	Ipconfig9              pulumi.StringPtrInput
	Iso                    pulumi.StringPtrInput
	Kvm                    pulumi.BoolPtrInput
	// Deprecated: Use `network.macaddr` to access the auto generated MAC address
	Mac    pulumi.StringPtrInput
	Memory pulumi.IntPtrInput
	// The VM name
	Name       pulumi.StringPtrInput
	Nameserver pulumi.StringPtrInput
	Networks   QemuVMNetworkArrayInput
	// Deprecated: Use `network` instead
	Nic  pulumi.StringPtrInput
	Numa pulumi.BoolPtrInput
	// VM autostart on boot
	Onboot pulumi.BoolPtrInput
	// VM autostart on create
	Oncreate        pulumi.BoolPtrInput
	OsNetworkConfig pulumi.StringPtrInput
	OsType          pulumi.StringPtrInput
	Pool            pulumi.StringPtrInput
	// Deprecated: do not use anymore
	Preprovision pulumi.BoolPtrInput
	Pxe          pulumi.BoolPtrInput
	QemuOs       pulumi.StringPtrInput
	Scsihw       pulumi.StringPtrInput
	Searchdomain pulumi.StringPtrInput
	Serials      QemuVMSerialArrayInput
	Sockets      pulumi.IntPtrInput
	// Use to pass instance ip address, redundant
	SshForwardIp  pulumi.StringPtrInput
	SshPrivateKey pulumi.StringPtrInput
	SshUser       pulumi.StringPtrInput
	Sshkeys       pulumi.StringPtrInput
	// Startup order of the VM
	Startup pulumi.StringPtrInput
	// Deprecated: Use `disk.storage` instead
	Storage pulumi.StringPtrInput
	// Deprecated: Use `disk.type` instead
	StorageType pulumi.StringPtrInput
	// Enable tablet mode in the VM
	Tablet pulumi.BoolPtrInput
	Tags   pulumi.StringPtrInput
	// The node where VM goes to
	TargetNode pulumi.StringInput
	Usbs       QemuVMUsbArrayInput
	Vcpus      pulumi.IntPtrInput
	Vgas       QemuVMVgaArrayInput
	// Deprecated: Use `network.tag` instead
	Vlan pulumi.IntPtrInput
	// The VM identifier in proxmox (100-999999999)
	Vmid pulumi.IntPtrInput
}

func (QemuVMArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*qemuVMArgs)(nil)).Elem()
}

type QemuVMInput interface {
	pulumi.Input

	ToQemuVMOutput() QemuVMOutput
	ToQemuVMOutputWithContext(ctx context.Context) QemuVMOutput
}

func (*QemuVM) ElementType() reflect.Type {
	return reflect.TypeOf((**QemuVM)(nil)).Elem()
}

func (i *QemuVM) ToQemuVMOutput() QemuVMOutput {
	return i.ToQemuVMOutputWithContext(context.Background())
}

func (i *QemuVM) ToQemuVMOutputWithContext(ctx context.Context) QemuVMOutput {
	return pulumi.ToOutputWithContext(ctx, i).(QemuVMOutput)
}

// QemuVMArrayInput is an input type that accepts QemuVMArray and QemuVMArrayOutput values.
// You can construct a concrete instance of `QemuVMArrayInput` via:
//
//	QemuVMArray{ QemuVMArgs{...} }
type QemuVMArrayInput interface {
	pulumi.Input

	ToQemuVMArrayOutput() QemuVMArrayOutput
	ToQemuVMArrayOutputWithContext(context.Context) QemuVMArrayOutput
}

type QemuVMArray []QemuVMInput

func (QemuVMArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*QemuVM)(nil)).Elem()
}

func (i QemuVMArray) ToQemuVMArrayOutput() QemuVMArrayOutput {
	return i.ToQemuVMArrayOutputWithContext(context.Background())
}

func (i QemuVMArray) ToQemuVMArrayOutputWithContext(ctx context.Context) QemuVMArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(QemuVMArrayOutput)
}

// QemuVMMapInput is an input type that accepts QemuVMMap and QemuVMMapOutput values.
// You can construct a concrete instance of `QemuVMMapInput` via:
//
//	QemuVMMap{ "key": QemuVMArgs{...} }
type QemuVMMapInput interface {
	pulumi.Input

	ToQemuVMMapOutput() QemuVMMapOutput
	ToQemuVMMapOutputWithContext(context.Context) QemuVMMapOutput
}

type QemuVMMap map[string]QemuVMInput

func (QemuVMMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*QemuVM)(nil)).Elem()
}

func (i QemuVMMap) ToQemuVMMapOutput() QemuVMMapOutput {
	return i.ToQemuVMMapOutputWithContext(context.Background())
}

func (i QemuVMMap) ToQemuVMMapOutputWithContext(ctx context.Context) QemuVMMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(QemuVMMapOutput)
}

type QemuVMOutput struct{ *pulumi.OutputState }

func (QemuVMOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**QemuVM)(nil)).Elem()
}

func (o QemuVMOutput) ToQemuVMOutput() QemuVMOutput {
	return o
}

func (o QemuVMOutput) ToQemuVMOutputWithContext(ctx context.Context) QemuVMOutput {
	return o
}

func (o QemuVMOutput) AdditionalWait() pulumi.IntPtrOutput {
	return o.ApplyT(func(v *QemuVM) pulumi.IntPtrOutput { return v.AdditionalWait }).(pulumi.IntPtrOutput)
}

func (o QemuVMOutput) Agent() pulumi.IntPtrOutput {
	return o.ApplyT(func(v *QemuVM) pulumi.IntPtrOutput { return v.Agent }).(pulumi.IntPtrOutput)
}

func (o QemuVMOutput) Args() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *QemuVM) pulumi.StringPtrOutput { return v.Args }).(pulumi.StringPtrOutput)
}

// Automatically reboot the VM if any of the modified parameters requires a reboot to take effect.
func (o QemuVMOutput) AutomaticReboot() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *QemuVM) pulumi.BoolPtrOutput { return v.AutomaticReboot }).(pulumi.BoolPtrOutput)
}

func (o QemuVMOutput) Balloon() pulumi.IntPtrOutput {
	return o.ApplyT(func(v *QemuVM) pulumi.IntPtrOutput { return v.Balloon }).(pulumi.IntPtrOutput)
}

// The VM bios, it can be seabios or ovmf
func (o QemuVMOutput) Bios() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *QemuVM) pulumi.StringPtrOutput { return v.Bios }).(pulumi.StringPtrOutput)
}

// Boot order of the VM
func (o QemuVMOutput) Boot() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *QemuVM) pulumi.StringPtrOutput { return v.Boot }).(pulumi.StringPtrOutput)
}

func (o QemuVMOutput) Bootdisk() pulumi.StringOutput {
	return o.ApplyT(func(v *QemuVM) pulumi.StringOutput { return v.Bootdisk }).(pulumi.StringOutput)
}

// Deprecated: Use `network.bridge` instead
func (o QemuVMOutput) Bridge() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *QemuVM) pulumi.StringPtrOutput { return v.Bridge }).(pulumi.StringPtrOutput)
}

func (o QemuVMOutput) CiWait() pulumi.IntPtrOutput {
	return o.ApplyT(func(v *QemuVM) pulumi.IntPtrOutput { return v.CiWait }).(pulumi.IntPtrOutput)
}

func (o QemuVMOutput) Cicustom() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *QemuVM) pulumi.StringPtrOutput { return v.Cicustom }).(pulumi.StringPtrOutput)
}

func (o QemuVMOutput) Cipassword() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *QemuVM) pulumi.StringPtrOutput { return v.Cipassword }).(pulumi.StringPtrOutput)
}

func (o QemuVMOutput) Ciuser() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *QemuVM) pulumi.StringPtrOutput { return v.Ciuser }).(pulumi.StringPtrOutput)
}

func (o QemuVMOutput) Clone() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *QemuVM) pulumi.StringPtrOutput { return v.Clone }).(pulumi.StringPtrOutput)
}

func (o QemuVMOutput) CloneWait() pulumi.IntPtrOutput {
	return o.ApplyT(func(v *QemuVM) pulumi.IntPtrOutput { return v.CloneWait }).(pulumi.IntPtrOutput)
}

func (o QemuVMOutput) CloudinitCdromStorage() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *QemuVM) pulumi.StringPtrOutput { return v.CloudinitCdromStorage }).(pulumi.StringPtrOutput)
}

func (o QemuVMOutput) Cores() pulumi.IntPtrOutput {
	return o.ApplyT(func(v *QemuVM) pulumi.IntPtrOutput { return v.Cores }).(pulumi.IntPtrOutput)
}

func (o QemuVMOutput) Cpu() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *QemuVM) pulumi.StringPtrOutput { return v.Cpu }).(pulumi.StringPtrOutput)
}

// Use to track vm ipv4 address
func (o QemuVMOutput) DefaultIpv4Address() pulumi.StringOutput {
	return o.ApplyT(func(v *QemuVM) pulumi.StringOutput { return v.DefaultIpv4Address }).(pulumi.StringOutput)
}

// By default define SSH for provisioner info
func (o QemuVMOutput) DefineConnectionInfo() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *QemuVM) pulumi.BoolPtrOutput { return v.DefineConnectionInfo }).(pulumi.BoolPtrOutput)
}

// The VM description
func (o QemuVMOutput) Desc() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *QemuVM) pulumi.StringPtrOutput { return v.Desc }).(pulumi.StringPtrOutput)
}

// Deprecated: Use `disk.size` instead
func (o QemuVMOutput) DiskGb() pulumi.Float64PtrOutput {
	return o.ApplyT(func(v *QemuVM) pulumi.Float64PtrOutput { return v.DiskGb }).(pulumi.Float64PtrOutput)
}

func (o QemuVMOutput) Disks() QemuVMDiskArrayOutput {
	return o.ApplyT(func(v *QemuVM) QemuVMDiskArrayOutput { return v.Disks }).(QemuVMDiskArrayOutput)
}

func (o QemuVMOutput) ForceCreate() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *QemuVM) pulumi.BoolPtrOutput { return v.ForceCreate }).(pulumi.BoolPtrOutput)
}

func (o QemuVMOutput) ForceRecreateOnChangeOf() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *QemuVM) pulumi.StringPtrOutput { return v.ForceRecreateOnChangeOf }).(pulumi.StringPtrOutput)
}

func (o QemuVMOutput) FullClone() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *QemuVM) pulumi.BoolPtrOutput { return v.FullClone }).(pulumi.BoolPtrOutput)
}

// Deprecated: Use custom per-resource timeout instead. See https://www.terraform.io/docs/language/resources/syntax.html#operation-timeouts
func (o QemuVMOutput) GuestAgentReadyTimeout() pulumi.IntPtrOutput {
	return o.ApplyT(func(v *QemuVM) pulumi.IntPtrOutput { return v.GuestAgentReadyTimeout }).(pulumi.IntPtrOutput)
}

func (o QemuVMOutput) Hagroup() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *QemuVM) pulumi.StringPtrOutput { return v.Hagroup }).(pulumi.StringPtrOutput)
}

func (o QemuVMOutput) Hastate() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *QemuVM) pulumi.StringPtrOutput { return v.Hastate }).(pulumi.StringPtrOutput)
}

func (o QemuVMOutput) Hostpcis() QemuVMHostpciArrayOutput {
	return o.ApplyT(func(v *QemuVM) QemuVMHostpciArrayOutput { return v.Hostpcis }).(QemuVMHostpciArrayOutput)
}

func (o QemuVMOutput) Hotplug() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *QemuVM) pulumi.StringPtrOutput { return v.Hotplug }).(pulumi.StringPtrOutput)
}

func (o QemuVMOutput) Ipconfig0() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *QemuVM) pulumi.StringPtrOutput { return v.Ipconfig0 }).(pulumi.StringPtrOutput)
}

func (o QemuVMOutput) Ipconfig1() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *QemuVM) pulumi.StringPtrOutput { return v.Ipconfig1 }).(pulumi.StringPtrOutput)
}

func (o QemuVMOutput) Ipconfig10() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *QemuVM) pulumi.StringPtrOutput { return v.Ipconfig10 }).(pulumi.StringPtrOutput)
}

func (o QemuVMOutput) Ipconfig11() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *QemuVM) pulumi.StringPtrOutput { return v.Ipconfig11 }).(pulumi.StringPtrOutput)
}

func (o QemuVMOutput) Ipconfig12() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *QemuVM) pulumi.StringPtrOutput { return v.Ipconfig12 }).(pulumi.StringPtrOutput)
}

func (o QemuVMOutput) Ipconfig13() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *QemuVM) pulumi.StringPtrOutput { return v.Ipconfig13 }).(pulumi.StringPtrOutput)
}

func (o QemuVMOutput) Ipconfig14() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *QemuVM) pulumi.StringPtrOutput { return v.Ipconfig14 }).(pulumi.StringPtrOutput)
}

func (o QemuVMOutput) Ipconfig15() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *QemuVM) pulumi.StringPtrOutput { return v.Ipconfig15 }).(pulumi.StringPtrOutput)
}

func (o QemuVMOutput) Ipconfig2() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *QemuVM) pulumi.StringPtrOutput { return v.Ipconfig2 }).(pulumi.StringPtrOutput)
}

func (o QemuVMOutput) Ipconfig3() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *QemuVM) pulumi.StringPtrOutput { return v.Ipconfig3 }).(pulumi.StringPtrOutput)
}

func (o QemuVMOutput) Ipconfig4() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *QemuVM) pulumi.StringPtrOutput { return v.Ipconfig4 }).(pulumi.StringPtrOutput)
}

func (o QemuVMOutput) Ipconfig5() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *QemuVM) pulumi.StringPtrOutput { return v.Ipconfig5 }).(pulumi.StringPtrOutput)
}

func (o QemuVMOutput) Ipconfig6() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *QemuVM) pulumi.StringPtrOutput { return v.Ipconfig6 }).(pulumi.StringPtrOutput)
}

func (o QemuVMOutput) Ipconfig7() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *QemuVM) pulumi.StringPtrOutput { return v.Ipconfig7 }).(pulumi.StringPtrOutput)
}

func (o QemuVMOutput) Ipconfig8() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *QemuVM) pulumi.StringPtrOutput { return v.Ipconfig8 }).(pulumi.StringPtrOutput)
}

func (o QemuVMOutput) Ipconfig9() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *QemuVM) pulumi.StringPtrOutput { return v.Ipconfig9 }).(pulumi.StringPtrOutput)
}

func (o QemuVMOutput) Iso() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *QemuVM) pulumi.StringPtrOutput { return v.Iso }).(pulumi.StringPtrOutput)
}

func (o QemuVMOutput) Kvm() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *QemuVM) pulumi.BoolPtrOutput { return v.Kvm }).(pulumi.BoolPtrOutput)
}

// Deprecated: Use `network.macaddr` to access the auto generated MAC address
func (o QemuVMOutput) Mac() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *QemuVM) pulumi.StringPtrOutput { return v.Mac }).(pulumi.StringPtrOutput)
}

func (o QemuVMOutput) Memory() pulumi.IntPtrOutput {
	return o.ApplyT(func(v *QemuVM) pulumi.IntPtrOutput { return v.Memory }).(pulumi.IntPtrOutput)
}

// The VM name
func (o QemuVMOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v *QemuVM) pulumi.StringOutput { return v.Name }).(pulumi.StringOutput)
}

func (o QemuVMOutput) Nameserver() pulumi.StringOutput {
	return o.ApplyT(func(v *QemuVM) pulumi.StringOutput { return v.Nameserver }).(pulumi.StringOutput)
}

func (o QemuVMOutput) Networks() QemuVMNetworkArrayOutput {
	return o.ApplyT(func(v *QemuVM) QemuVMNetworkArrayOutput { return v.Networks }).(QemuVMNetworkArrayOutput)
}

// Deprecated: Use `network` instead
func (o QemuVMOutput) Nic() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *QemuVM) pulumi.StringPtrOutput { return v.Nic }).(pulumi.StringPtrOutput)
}

func (o QemuVMOutput) Numa() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *QemuVM) pulumi.BoolPtrOutput { return v.Numa }).(pulumi.BoolPtrOutput)
}

// VM autostart on boot
func (o QemuVMOutput) Onboot() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *QemuVM) pulumi.BoolPtrOutput { return v.Onboot }).(pulumi.BoolPtrOutput)
}

// VM autostart on create
func (o QemuVMOutput) Oncreate() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *QemuVM) pulumi.BoolPtrOutput { return v.Oncreate }).(pulumi.BoolPtrOutput)
}

func (o QemuVMOutput) OsNetworkConfig() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *QemuVM) pulumi.StringPtrOutput { return v.OsNetworkConfig }).(pulumi.StringPtrOutput)
}

func (o QemuVMOutput) OsType() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *QemuVM) pulumi.StringPtrOutput { return v.OsType }).(pulumi.StringPtrOutput)
}

func (o QemuVMOutput) Pool() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *QemuVM) pulumi.StringPtrOutput { return v.Pool }).(pulumi.StringPtrOutput)
}

// Deprecated: do not use anymore
func (o QemuVMOutput) Preprovision() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *QemuVM) pulumi.BoolPtrOutput { return v.Preprovision }).(pulumi.BoolPtrOutput)
}

func (o QemuVMOutput) Pxe() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *QemuVM) pulumi.BoolPtrOutput { return v.Pxe }).(pulumi.BoolPtrOutput)
}

func (o QemuVMOutput) QemuOs() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *QemuVM) pulumi.StringPtrOutput { return v.QemuOs }).(pulumi.StringPtrOutput)
}

// Internal variable, true if any of the modified parameters requires a reboot to take effect.
func (o QemuVMOutput) RebootRequired() pulumi.BoolOutput {
	return o.ApplyT(func(v *QemuVM) pulumi.BoolOutput { return v.RebootRequired }).(pulumi.BoolOutput)
}

func (o QemuVMOutput) Scsihw() pulumi.StringOutput {
	return o.ApplyT(func(v *QemuVM) pulumi.StringOutput { return v.Scsihw }).(pulumi.StringOutput)
}

func (o QemuVMOutput) Searchdomain() pulumi.StringOutput {
	return o.ApplyT(func(v *QemuVM) pulumi.StringOutput { return v.Searchdomain }).(pulumi.StringOutput)
}

func (o QemuVMOutput) Serials() QemuVMSerialArrayOutput {
	return o.ApplyT(func(v *QemuVM) QemuVMSerialArrayOutput { return v.Serials }).(QemuVMSerialArrayOutput)
}

func (o QemuVMOutput) Sockets() pulumi.IntPtrOutput {
	return o.ApplyT(func(v *QemuVM) pulumi.IntPtrOutput { return v.Sockets }).(pulumi.IntPtrOutput)
}

// Use to pass instance ip address, redundant
func (o QemuVMOutput) SshForwardIp() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *QemuVM) pulumi.StringPtrOutput { return v.SshForwardIp }).(pulumi.StringPtrOutput)
}

func (o QemuVMOutput) SshHost() pulumi.StringOutput {
	return o.ApplyT(func(v *QemuVM) pulumi.StringOutput { return v.SshHost }).(pulumi.StringOutput)
}

func (o QemuVMOutput) SshPort() pulumi.StringOutput {
	return o.ApplyT(func(v *QemuVM) pulumi.StringOutput { return v.SshPort }).(pulumi.StringOutput)
}

func (o QemuVMOutput) SshPrivateKey() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *QemuVM) pulumi.StringPtrOutput { return v.SshPrivateKey }).(pulumi.StringPtrOutput)
}

func (o QemuVMOutput) SshUser() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *QemuVM) pulumi.StringPtrOutput { return v.SshUser }).(pulumi.StringPtrOutput)
}

func (o QemuVMOutput) Sshkeys() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *QemuVM) pulumi.StringPtrOutput { return v.Sshkeys }).(pulumi.StringPtrOutput)
}

// Startup order of the VM
func (o QemuVMOutput) Startup() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *QemuVM) pulumi.StringPtrOutput { return v.Startup }).(pulumi.StringPtrOutput)
}

// Deprecated: Use `disk.storage` instead
func (o QemuVMOutput) Storage() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *QemuVM) pulumi.StringPtrOutput { return v.Storage }).(pulumi.StringPtrOutput)
}

// Deprecated: Use `disk.type` instead
func (o QemuVMOutput) StorageType() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *QemuVM) pulumi.StringPtrOutput { return v.StorageType }).(pulumi.StringPtrOutput)
}

// Enable tablet mode in the VM
func (o QemuVMOutput) Tablet() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *QemuVM) pulumi.BoolPtrOutput { return v.Tablet }).(pulumi.BoolPtrOutput)
}

func (o QemuVMOutput) Tags() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *QemuVM) pulumi.StringPtrOutput { return v.Tags }).(pulumi.StringPtrOutput)
}

// The node where VM goes to
func (o QemuVMOutput) TargetNode() pulumi.StringOutput {
	return o.ApplyT(func(v *QemuVM) pulumi.StringOutput { return v.TargetNode }).(pulumi.StringOutput)
}

// Record unused disks in proxmox. This is intended to be read-only for now.
func (o QemuVMOutput) UnusedDisks() QemuVMUnusedDiskArrayOutput {
	return o.ApplyT(func(v *QemuVM) QemuVMUnusedDiskArrayOutput { return v.UnusedDisks }).(QemuVMUnusedDiskArrayOutput)
}

func (o QemuVMOutput) Usbs() QemuVMUsbArrayOutput {
	return o.ApplyT(func(v *QemuVM) QemuVMUsbArrayOutput { return v.Usbs }).(QemuVMUsbArrayOutput)
}

func (o QemuVMOutput) Vcpus() pulumi.IntPtrOutput {
	return o.ApplyT(func(v *QemuVM) pulumi.IntPtrOutput { return v.Vcpus }).(pulumi.IntPtrOutput)
}

func (o QemuVMOutput) Vgas() QemuVMVgaArrayOutput {
	return o.ApplyT(func(v *QemuVM) QemuVMVgaArrayOutput { return v.Vgas }).(QemuVMVgaArrayOutput)
}

// Deprecated: Use `network.tag` instead
func (o QemuVMOutput) Vlan() pulumi.IntPtrOutput {
	return o.ApplyT(func(v *QemuVM) pulumi.IntPtrOutput { return v.Vlan }).(pulumi.IntPtrOutput)
}

// The VM identifier in proxmox (100-999999999)
func (o QemuVMOutput) Vmid() pulumi.IntOutput {
	return o.ApplyT(func(v *QemuVM) pulumi.IntOutput { return v.Vmid }).(pulumi.IntOutput)
}

type QemuVMArrayOutput struct{ *pulumi.OutputState }

func (QemuVMArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*QemuVM)(nil)).Elem()
}

func (o QemuVMArrayOutput) ToQemuVMArrayOutput() QemuVMArrayOutput {
	return o
}

func (o QemuVMArrayOutput) ToQemuVMArrayOutputWithContext(ctx context.Context) QemuVMArrayOutput {
	return o
}

func (o QemuVMArrayOutput) Index(i pulumi.IntInput) QemuVMOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *QemuVM {
		return vs[0].([]*QemuVM)[vs[1].(int)]
	}).(QemuVMOutput)
}

type QemuVMMapOutput struct{ *pulumi.OutputState }

func (QemuVMMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*QemuVM)(nil)).Elem()
}

func (o QemuVMMapOutput) ToQemuVMMapOutput() QemuVMMapOutput {
	return o
}

func (o QemuVMMapOutput) ToQemuVMMapOutputWithContext(ctx context.Context) QemuVMMapOutput {
	return o
}

func (o QemuVMMapOutput) MapIndex(k pulumi.StringInput) QemuVMOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *QemuVM {
		return vs[0].(map[string]*QemuVM)[vs[1].(string)]
	}).(QemuVMOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*QemuVMInput)(nil)).Elem(), &QemuVM{})
	pulumi.RegisterInputType(reflect.TypeOf((*QemuVMArrayInput)(nil)).Elem(), QemuVMArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*QemuVMMapInput)(nil)).Elem(), QemuVMMap{})
	pulumi.RegisterOutputType(QemuVMOutput{})
	pulumi.RegisterOutputType(QemuVMArrayOutput{})
	pulumi.RegisterOutputType(QemuVMMapOutput{})
}
