---
name: Pipeline

on:
  pull_request:
  push:
    branches:
      - "*"
    paths:
      - "provider/**"
      - "sdk/**"
      - "Makefile"
      - ".goreleaser.yml"

env:
  PROVIDER: proxmoxve
  GO111MODULE: "on"
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  provider:
    runs-on: ubuntu-latest
    name: Build Provider
    strategy:
      max-parallel: 4
      matrix:
        go-version: [1.18.x]
        golangci-lint-version: [v1.50.1]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: "${{ matrix.go-version }}"

      - name: Install pulumictl
        uses: jaxxstorm/action-install-gh-release@v1.9.0
        with:
          repo: pulumi/pulumictl
      - name: Install Pulumi CLI
        uses: pulumi/setup-pulumi@v2

      - name: Build Provider
        run: make provider
      - name: Lint Provider
        uses: golangci/golangci-lint-action@v3
        with:
          version: "${{ matrix.golangci-lint-version }}"
          working-directory: provider
          args: -c ../.golangci.yml
          skip-pkg-cache: true
          skip-build-cache: true

  sdk:
    runs-on: ubuntu-latest
    name: Build SDK
    strategy:
      max-parallel: 4
      matrix:
        go-version: [1.18.x]
        node-version: [16]
        language:
          - go
          - nodejs


    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: "${{ matrix.go-version }}"
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "${{ matrix.node-version }}"

      - name: Install pulumictl
        uses: jaxxstorm/action-install-gh-release@v1.9.0
        with:
          repo: pulumi/pulumictl
      - name: Install Pulumi CLI
        uses: pulumi/setup-pulumi@v2

      - name: Build SDK
        run: make build_${{ matrix.language }}

